spring:
  application:
    name: DesafioDesignPattern

  datasource:
    url: jdbc:postgresql://localhost:5432/gofdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

debug: true